.gitignore, app/build.gradle.kts, app/google-services.json, app/src/main/java/info/imdang/imdang/model/insight/InsightVo.kt, app/src/main/java/info/imdang/imdang/ui/login/LoginActivity.kt, buildSrc/src/main/java/DevConfig.kt, buildSrc/src/main/java/ProductConfig.kt, component/build.gradle.kts, data/build.gradle.kts, data/src/main/java/info/imdang/data/constant/RemoteConstant.kt, proguard-rules.pro, remote/build.gradle.kts
- resolve #9
- release keystore 생성
- 생성된 release keystore를 이용한 release build 서명
- release build를 하기 위해서는 [Build Key](https://www.notion.so/Build-Key-76b790a002cd4f83a6d21df18aca860f?pvs=4) 페이지의 첨부파일 2개를 project 최상단에 추가해야 합니다.
- Build Variants를 productRelease로 설정하셔서 정상적으로 빌드되면 됩니다.
=> release 빌드 설정

app/src/main/AndroidManifest.xml, app/src/main/java/info/imdang/imdang/base/BaseActivity.kt, app/src/main/java/info/imdang/imdang/common/ext/ActivityExt.kt, app/src/main/java/info/imdang/imdang/common/ext/ViewExt.kt, app/src/main/java/info/imdang/imdang/common/util/KeyboardVisibilityUtils.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/res/layout/activity_basic_information.xml, component/src/main/res/values/strings.xml
- resolve #18
- BaseActivity에 onShowKeyboard, onHideKeyboard 함수 정의
- BaseActivity에 keyboard visible 상태를 가지는 `isVisibleKeyboard` 변수 정의
- 기본 정보 입력화면에서 키보드 노출에 따른 버튼 변경 구현
-
=> 키보드 상태에 따른 버튼 변경

app/src/main/AndroidManifest.xml, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/java/info/imdang/imdang/ui/main/MainActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightPagerAdapter.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt, app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightBasicInfoFragment.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_write_insight.xml, app/src/main/res/layout/fragment_write_insight_basic_info.xml, component/src/main/res/drawable/gradient_gray25_100.xml, component/src/main/res/drawable/ic_image.xml, component/src/main/res/drawable/ic_plus.xml, component/src/main/res/drawable/sr_gray100_all8.xml, component/src/main/res/drawable/sr_gray50_gray100_all4.xml, component/src/main/res/drawable/sr_white_gray100_all6.xml, component/src/main/res/values/strings.xml, component/src/main/res/values/text-styles.xml
- resolve #20
- 인사이트 작성 - 기본 정보 UI 구현
-
=> 인사이트 작성 - 기본 정보 UI 구현

app/src/main/java/info/imdang/imdang/common/ext/EditTextExt.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt, app/src/main/res/layout/activity_basic_information.xml, buildSrc/src/main/java/AppConfig.kt, component/src/main/res/drawable/ic_cancel.xml, component/src/main/res/drawable/ic_check.xml, component/src/main/res/drawable/ic_exclamation_mark_red.xml, component/src/main/res/drawable/sr_cursor.xml, component/src/main/res/drawable/sr_orange50_orange500_all8.xml, component/src/main/res/drawable/sr_white_red_all8.xml, component/src/main/res/values/colors.xml, component/src/main/res/values/dimens.xml, component/src/main/res/values/strings.xml
- resolve #4 
- 기본정보입력시 오류 체크 하는 기능 구현
-
=> 기본정보입력시 오류 체크 하는 기능 구현

app/src/main/java/info/imdang/imdang/base/BaseDialog.kt, app/src/main/java/info/imdang/imdang/model/insight/InsightVo.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailEvent.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt, app/src/main/java/info/imdang/imdang/ui/insight/bottomsheet/MyInsightsBottomSheet.kt, app/src/main/res/layout/bottom_sheet_my_insights.xml, app/src/main/res/layout/dialog_exchange.xml, app/src/main/res/layout/item_insight_detail_basic_info.xml, app/src/main/res/layout/item_insight_detail_my_insight.xml, component/src/main/res/drawable/ic_check_for_dialog.xml, component/src/main/res/drawable/selector_white_gray100_all100.xml, component/src/main/res/drawable/sr_white_all20.xml, component/src/main/res/values/strings.xml, component/src/main/res/values/text-styles.xml
- resolve #28
- 인사이트 상세 교환 팝업 구현
-
=> 인사이트 상세 교환 팝업 구현

app/src/main/AndroidManifest.xml, app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt, app/src/main/java/info/imdang/imdang/ui/main/home/search/map/SearchByMapActivity.kt, app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt, app/src/main/java/info/imdang/imdang/ui/main/storage/map/StorageByMapActivity.kt, app/src/main/res/layout/activity_search_by_map.xml, app/src/main/res/layout/activity_storage_by_map.xml, app/src/main/res/layout/fragment_storage.xml, component/src/main/res/values/strings.xml
- resolve #34
- 지도 서비스 안내 화면 구현
-
=> 지도 서비스 안내 화면 구현

app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt, app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt, app/src/main/java/info/imdang/imdang/ui/main/storage/StorageViewModel.kt, app/src/main/res/layout/fragment_home_search.xml, app/src/main/res/layout/fragment_storage.xml, component/src/main/res/drawable/ic_ban.xml, component/src/main/res/drawable/sr_dash_gray50_gray100_all8.xml, component/src/main/res/drawable/sr_gray50_all100.xml, component/src/main/res/values/strings.xml
- resolve #49
- 홈 : 내가 다녀온 단지의 다른 인사이트 목록 없는 경우 UI 구현
- 보관함 : 인사이트 목록 없는 경우 UI 구현
-
=> 인사이트 내역 없는 경우 UI 구현

app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt, data/src/main/java/info/imdang/data/datasource/remote/AuthRemoteDataSource.kt, data/src/main/java/info/imdang/data/model/request/auth/OnboardingRequest.kt, data/src/main/java/info/imdang/data/repository/AuthRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/model/auth/OnboardingDto.kt, domain/src/main/java/info/imdang/domain/repository/AuthRepository.kt, domain/src/main/java/info/imdang/domain/usecase/auth/OnboardingJoinUseCase.kt, remote/src/main/java/info/imdang/remote/datasource/AuthRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/service/AuthService.kt
- resolve #4
- 기본 정보 입력시 api 연결
-
=> feat : 기본 정보 입력시 api 연결

app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt, app/src/main/java/info/imdang/imdang/ui/common/CommonDialog.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt, app/src/main/res/layout/dialog_common.xml, component/src/main/res/values/strings.xml, component/src/main/res/values/text-styles.xml
- resolve #54
- 인사이트 신고하기 팝업 구현
-
=> 인사이트 신고하기 팝업 구현

app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt
- resolve #63
- InsightDetailVo isReported 추가
-
=> InsightDetailVo isReported 추가

app/src/main/java/info/imdang/imdang/common/bindingadapter/ImageViewBindingAdapter.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt, app/src/main/java/info/imdang/imdang/ui/join/bottomsheet/ServiceTermBottomSheet.kt, app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingViewModel.kt, app/src/main/res/layout/bottom_sheet_service_term.xml, app/src/main/res/layout/fragment_onboarding.xml, component/src/main/res/values/strings.xml
- resolve #66 
- 서비스 이용약관 화면 구현
- 온보딩 2, 3 이미지 수정
-
=> 서비스이용약관 화면 구현

app/src/main/java/info/imdang/imdang/base/BasePagingDataAdapter.kt, app/src/main/java/info/imdang/imdang/common/bindingadapter/RecyclerViewBindingAdapter.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt, app/src/main/java/info/imdang/imdang/ui/insight/bottomsheet/ExchangeItemsBottomSheet.kt, app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchViewModel.kt, app/src/main/res/layout/bottom_sheet_exchange_items.xml, app/src/main/res/layout/item_insight_detail_my_insight.xml, data/src/main/java/info/imdang/data/repository/MyInsightRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/repository/MyInsightRepository.kt, domain/src/main/java/info/imdang/domain/usecase/myinsight/GetMyInsightsWithPagingUseCase.kt
- resolve #75
- 내 인사이트 목록 무한 스크롤 구현
-
=> 내 인사이트 목록 무한 스크롤 구현

app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt, app/src/main/java/info/imdang/imdang/ui/main/storage/StorageViewModel.kt, app/src/main/res/layout/fragment_storage.xml
- resolve #79
- 보관함 스크롤 시 상단 타이틀 변경
-
=> 보관함 스크롤 시 상단 타이틀 변경

app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightEvent.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt, component/src/main/java/info/imdang/component/Toast.kt, component/src/main/res/drawable/bg_toast.xml, component/src/main/res/layout/toast_common.xml, component/src/main/res/values/colors.xml
- resolve #81
- 다음 버튼 클릭 후 % 변경되도록 수정
- 인사이트 작성 완료 팝업 확인 클릭 시 인사이트 상세 화면으로 이동
-
=> 인사이트 작성 qa

app/src/main/java/info/imdang/imdang/model/notification/NotificationItem.kt, app/src/main/java/info/imdang/imdang/model/notification/NotificationVo.kt, app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationActivity.kt, app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationItemDecoration.kt, app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationViewModel.kt, app/src/main/res/layout/activity_notification.xml, app/src/main/res/layout/item_notification_empty.xml
- resolve #83
- 알림 빈 화면 UI 구현
-
=> 알림 빈 화면 UI 구현

app/src/main/java/info/imdang/imdang/common/bindingadapter/ChipBindingAdapter.kt, app/src/main/java/info/imdang/imdang/common/bindingadapter/TextViewBindingAdapter.kt, app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeAdapter.kt, app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeFragment.kt, app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeViewModel.kt, app/src/main/java/info/imdang/imdang/ui/main/home/history/HomeHistoryRequestedFragment.kt, app/src/main/res/layout/fragment_home_exchange.xml, app/src/main/res/layout/fragment_home_history_requested.xml, component/src/main/res/values/strings.xml, data/src/main/java/info/imdang/data/datasource/remote/MyExchangeRemoteDataSource.kt, data/src/main/java/info/imdang/data/di/RepositoryModule.kt, data/src/main/java/info/imdang/data/repository/MyExchangeRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/model/common/MyExchangesParams.kt, domain/src/main/java/info/imdang/domain/repository/MyExchangeRepository.kt, domain/src/main/java/info/imdang/domain/usecase/myexchange/GetMyExchangeUseCase.kt, domain/src/main/java/info/imdang/domain/usecase/myexchange/GetOthersExchangeUseCase.kt, remote/src/main/java/info/imdang/remote/datasource/MyExchangeRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/di/RemoteDataSourceModule.kt, remote/src/main/java/info/imdang/remote/di/ServiceModule.kt, remote/src/main/java/info/imdang/remote/service/MyExchangeService.kt
=> 교환소 api 연동

app/src/main/java/info/imdang/imdang/model/coupon/CouponVo.kt, app/src/main/java/info/imdang/imdang/model/insight/ExchangeRequestStatus.kt, app/src/main/java/info/imdang/imdang/model/insight/InsightDetailItem.kt, app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt, app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt, app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeViewModel.kt, app/src/main/res/layout/activity_insight_detail.xml, app/src/main/res/layout/fragment_home_exchange.xml, app/src/main/res/layout/item_insight_detail_good_news.xml, data/src/main/java/info/imdang/data/datasource/remote/CouponRemoteDataSource.kt, data/src/main/java/info/imdang/data/datasource/remote/ExchangeRemoteDataSource.kt, data/src/main/java/info/imdang/data/model/request/exchange/RequestExchangeRequest.kt, data/src/main/java/info/imdang/data/model/request/exchange/ResponseExchangeRequest.kt, data/src/main/java/info/imdang/data/model/response/coupon/CouponResponse.kt, data/src/main/java/info/imdang/data/model/response/insight/InsightDetailResponse.kt, data/src/main/java/info/imdang/data/repository/CouponRepositoryImpl.kt, data/src/main/java/info/imdang/data/repository/ExchangeRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/model/coupon/CouponDto.kt, domain/src/main/java/info/imdang/domain/model/insight/InsightDetailDto.kt, domain/src/main/java/info/imdang/domain/repository/CouponRepository.kt, domain/src/main/java/info/imdang/domain/repository/ExchangeRepository.kt, domain/src/main/java/info/imdang/domain/usecase/coupon/GetCouponUseCase.kt, domain/src/main/java/info/imdang/domain/usecase/exchange/AcceptExchangeUseCase.kt, domain/src/main/java/info/imdang/domain/usecase/exchange/RejectExchangeUseCase.kt, domain/src/main/java/info/imdang/domain/usecase/exchange/RequestExchangeUseCase.kt, remote/src/main/java/info/imdang/remote/datasource/CouponRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/datasource/ExchangeRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/service/CouponService.kt, remote/src/main/java/info/imdang/remote/service/ExchangeService.kt
- resolve #69
- 인사이트 교환 기능 구현
-
=> 인사이트 교환 기능 구현

app/build.gradle.kts, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt, data/src/main/java/info/imdang/data/model/request/auth/OnboardingRequest.kt, domain/src/main/java/info/imdang/domain/model/auth/OnboardingDto.kt, gradle/libs.versions.toml
- FCM 토큰 값 추가
- resolve #4 
- 
-
=> 기본 정보 입력 api 수정

app/src/main/java/info/imdang/imdang/ui/main/storage/StorageViewModel.kt, app/src/main/res/layout/fragment_storage.xml
- resolve #95
- 보관함 빈 화면 조건 수정
-
=> 보관함 빈 화면 조건 수정

app/src/main/java/info/imdang/imdang/ui/main/MainViewModel.kt, data/src/main/java/info/imdang/data/constant/ResponseCode.kt, data/src/main/java/info/imdang/data/datasource/remote/AuthRemoteDataSource.kt, data/src/main/java/info/imdang/data/di/NetworkModule.kt, data/src/main/java/info/imdang/data/model/request/auth/ReissueTokenRequest.kt, local/src/main/java/info/imdang/local/datasource/AuthLocalDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/datasource/AuthRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/service/AuthService.kt
- resolve #104
- 토큰 갱신 로직 수정
-
=> 토큰 갱신 로직 수정

app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightBasicInfoFragment.kt
- resolve #105
- 이미지 업로드 시 파일 확장자 추가
-
=> 이미지 업로드 시 파일 확장자 추가

app/src/main/java/info/imdang/imdang/ui/main/home/HomeViewModel.kt, app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeViewModel.kt
- resolve #109
- 무료 패스권 안내 팝업 표시 로직 수정
-
=> 무료 패스권 안내 팝업 표시 로직 수정

app/src/main/java/info/imdang/imdang/ui/main/MainViewModel.kt, app/src/main/java/info/imdang/imdang/ui/main/home/search/region/SearchByRegionActivity.kt, app/src/main/java/info/imdang/imdang/ui/main/home/search/region/SearchByRegionViewModel.kt, app/src/main/java/info/imdang/imdang/ui/main/storage/StorageViewModel.kt, app/src/main/java/info/imdang/imdang/ui/write/review/WriteOverallReviewActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/summary/WriteInsightSummaryActivity.kt, app/src/main/res/layout/activity_write_insight_summary.xml, app/src/main/res/layout/activity_write_overall_review.xml, data/src/main/java/info/imdang/data/model/request/coupon/IssueCouponRequest.kt, data/src/main/java/info/imdang/data/repository/CouponRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/repository/CouponRepository.kt, domain/src/main/java/info/imdang/domain/usecase/coupon/IssueCouponUseCase.kt
- resolve #115
- 무료 쿠폰 id 수정
- 지역으로 찾기 오류 수정
- 인사이트 요약, 총평 작성 UI 수정
-
=> 홈 인사이트 작성 QA

data/src/main/java/info/imdang/data/datasource/remote/CouponRemoteDataSource.kt, data/src/main/java/info/imdang/data/datasource/remote/MyCouponRemoteDataSource.kt, data/src/main/java/info/imdang/data/di/RepositoryModule.kt, data/src/main/java/info/imdang/data/repository/CouponRepositoryImpl.kt, data/src/main/java/info/imdang/data/repository/MyCouponRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/repository/CouponRepository.kt, domain/src/main/java/info/imdang/domain/repository/MyCouponRepository.kt, domain/src/main/java/info/imdang/domain/usecase/coupon/GetCouponUseCase.kt, remote/src/main/java/info/imdang/remote/datasource/CouponRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/datasource/MyCouponRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/di/RemoteDataSourceModule.kt, remote/src/main/java/info/imdang/remote/di/ServiceModule.kt, remote/src/main/java/info/imdang/remote/service/CouponService.kt, remote/src/main/java/info/imdang/remote/service/MyCouponService.kt
- resolve #118
- 쿠폰 조회 API 수정
-
=> 쿠폰 조회 API 수정

app/src/main/java/info/imdang/imdang/model/notification/NotificationCategory.kt, app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationViewModel.kt, app/src/main/res/layout/item_notification.xml
- resolve #120
- 알림 목록 UI 수정
-
=> 알림 목록 UI 수정

app/src/main/res/layout/activity_my.xml, data/src/main/java/info/imdang/data/datasource/remote/MyPageRemoteDataSource.kt, data/src/main/java/info/imdang/data/model/response/mypage/MyPageResponse.kt, data/src/main/java/info/imdang/data/repository/MyPageRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/model/mypage/MyPageDto.kt, domain/src/main/java/info/imdang/domain/repository/MyPageRepository.kt, domain/src/main/java/info/imdang/domain/usecase/mypage/GetMyPageInfoUseCase.kt, remote/src/main/java/info/imdang/remote/datasource/MyPageRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/service/MyPageService.kt
- resolve #124
-  마이페이지 API 수정
-
=>  마이페이지 API 수정

app/src/main/res/xml/network_security_config.xml, buildSrc/src/main/java/DevConfig.kt
- resolve #127
- 개발/운영 서버 분리
-
=> 개발/운영 서버 분리

app/src/main/java/info/imdang/imdang/common/SpaceItemDecoration.kt, app/src/main/java/info/imdang/imdang/ui/main/MainActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt, app/src/main/res/layout/fragment_home_search.xml
- resolve #131
- 인사이트 작성 후 홈 보관함 초기화
-
=> 인사이트 작성 후 홈 보관함 초기화

app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt, app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt, app/src/main/res/layout/activity_basic_information.xml, component/src/main/res/values/strings.xml, data/src/main/java/info/imdang/data/model/request/auth/OnboardingRequest.kt, domain/src/main/java/info/imdang/domain/model/auth/OnboardingDto.kt
=> 기본정보입력 화면 수정

app/src/main/java/info/imdang/imdang/common/util/EventTracker.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt
- resolve #138 
- 인사이트 중복 작성 방지
-
=> 인사이트 중복 작성 방지

app/src/main/java/info/imdang/imdang/ui/main/MainViewModel.kt, data/src/main/java/info/imdang/data/datasource/remote/CouponRemoteDataSource.kt, data/src/main/java/info/imdang/data/model/request/coupon/IssueCouponRequest.kt, data/src/main/java/info/imdang/data/repository/CouponRepositoryImpl.kt, domain/src/main/java/info/imdang/domain/repository/CouponRepository.kt, domain/src/main/java/info/imdang/domain/usecase/coupon/IssueCouponUseCase.kt, remote/src/main/java/info/imdang/remote/datasource/CouponRemoteDataSourceImpl.kt, remote/src/main/java/info/imdang/remote/service/CouponService.kt
- resolve #140 
- 패스권 발급 API 요청 파라미터 삭제
-
=> 패스권 발급 API 요청 파라미터 삭제

app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt, app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightBasicInfoFragment.kt, app/src/main/res/layout/activity_write_insight.xml, app/src/main/res/layout/fragment_write_insight_basic_info.xml, component/src/main/res/values/strings.xml
=> [QA] 인사이트작성 UI수정 
